 
! This file is AUTOGENERATED!!!!
! Do not edit this file; edit m_wcml_quantity.m4 and regenerate.
!
!
module m_wcml_parameter

  use FoX_wxml, only: xmlf_t
  use FoX_wxml, only: xml_NewElement, xml_AddAttribute
  use FoX_wxml, only: xml_EndElement
  use m_wcml_stml, only: stmAddValue

  implicit none
  private

  integer, parameter ::  sp = selected_real_kind(6,30)
  integer, parameter ::  dp = selected_real_kind(14,100)

  interface cmlAddparameter
     module procedure parameterScaRealDp
     module procedure parameterArrRealDpSi
     module procedure parameterArrRealDpSh
     module procedure parameterMatRealDpSi
     module procedure parameterMatRealDpSh
     module procedure parameterScaRealSp
     module procedure parameterArrRealSpSi
     module procedure parameterArrRealSpSh
     module procedure parameterMatRealSpSi
     module procedure parameterMatRealSpSh
     module procedure parameterScaInt
     module procedure parameterArrIntSi
     module procedure parameterArrIntSh
     module procedure parameterMatIntSi
     module procedure parameterMatIntSh
     module procedure parameterScaLg
     module procedure parameterArrLgSi
     module procedure parameterArrLgSh
     module procedure parameterMatLgSi
     module procedure parameterMatLgSh
     module procedure parameterScaCh
     module procedure parameterArrChSi
     module procedure parameterArrChSh
     module procedure parameterMatChSi
     module procedure parameterMatChSh

  end interface cmlAddparameter

  public :: cmlAddparameter
  public :: cmlStartparameterList
  public :: cmlEndparameterList

contains

  subroutine cmlStartparameterList(xf, name, id, title, dictRef, convention, ref, role)

    type(xmlf_t), intent(inout) :: xf
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

 
    call xml_NewElement(xf, "parameterList")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    
  end subroutine cmlStartparameterList

  subroutine cmlEndparameterList(xf)

    type(xmlf_t), intent(inout) :: xf

    Call xml_EndElement(xf, "parameterList")
    
  end subroutine cmlEndparameterList


  subroutine parameterScaRealDp &
    (xf, value, name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    real(dp) , intent(in) :: value
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units ,fmt=fmt )
    call xml_EndElement(xf, "parameter")

  end subroutine parameterScaRealDp

  subroutine parameterScaRealSp &
    (xf, value, name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    real(sp) , intent(in) :: value
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units ,fmt=fmt )
    call xml_EndElement(xf, "parameter")

  end subroutine parameterScaRealSp

  subroutine parameterScaInt &
    (xf, value, name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    integer , intent(in) :: value
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units  )
    call xml_EndElement(xf, "parameter")

  end subroutine parameterScaInt

  subroutine parameterScaLg &
    (xf, value, name, id, title, dictRef, convention, ref, role  )

    type(xmlf_t), intent(inout)              :: xf
    logical , intent(in) :: value
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value   )
    call xml_EndElement(xf, "parameter")

  end subroutine parameterScaLg

  subroutine parameterScaCh &
    (xf, value, name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    character(len=*) , intent(in) :: value
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units  )
    call xml_EndElement(xf, "parameter")

  end subroutine parameterScaCh


  subroutine parameterArrRealDpSi &
    (xf, value, nvalue,  name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nvalue
    real(dp) , intent(in) :: value(* )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nvalue) , units=units ,fmt=fmt )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrRealDpSi

  subroutine parameterArrRealSpSi &
    (xf, value, nvalue,  name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nvalue
    real(sp) , intent(in) :: value(* )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nvalue) , units=units ,fmt=fmt )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrRealSpSi

  subroutine parameterArrIntSi &
    (xf, value, nvalue,  name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nvalue
    integer , intent(in) :: value(* )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nvalue) , units=units  )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrIntSi

  subroutine parameterArrLgSi &
    (xf, value, nvalue,  name, id, title, dictRef, convention, ref, role  )

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nvalue
    logical , intent(in) :: value(* )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nvalue)   )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrLgSi

  subroutine parameterArrChSi &
    (xf, value, nvalue,  name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nvalue
    character(len=*) , intent(in) :: value(* )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nvalue) , units=units  )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrChSi


  subroutine parameterArrRealDpSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    real(dp) , intent(in) :: value(: )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units ,fmt=fmt )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrRealDpSh

  subroutine parameterArrRealSpSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    real(sp) , intent(in) :: value(: )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units ,fmt=fmt )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrRealSpSh

  subroutine parameterArrIntSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    integer , intent(in) :: value(: )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units  )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrIntSh

  subroutine parameterArrLgSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role  )

    type(xmlf_t), intent(inout)              :: xf
    logical , intent(in) :: value(: )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value   )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrLgSh

  subroutine parameterArrChSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    character(len=*) , intent(in) :: value(: )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

    character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units  )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterArrChSh


  subroutine parameterMatRealDpSi &
    (xf, value, nrows, ncols,  name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nrows, ncols
    real(dp) , intent(in) :: value(nrows, * )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

     character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nrows,:ncols) , units=units , fmt=fmt )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatRealDpSi

  subroutine parameterMatRealSpSi &
    (xf, value, nrows, ncols,  name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nrows, ncols
    real(sp) , intent(in) :: value(nrows, * )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

     character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nrows,:ncols) , units=units , fmt=fmt )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatRealSpSi

  subroutine parameterMatIntSi &
    (xf, value, nrows, ncols,  name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nrows, ncols
    integer , intent(in) :: value(nrows, * )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

     character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nrows,:ncols) , units=units  )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatIntSi

  subroutine parameterMatLgSi &
    (xf, value, nrows, ncols,  name, id, title, dictRef, convention, ref, role  )

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nrows, ncols
    logical , intent(in) :: value(nrows, * )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nrows,:ncols)   )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatLgSi

  subroutine parameterMatChSi &
    (xf, value, nrows, ncols,  name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    integer, intent(in)                      :: nrows, ncols
    character(len=*) , intent(in) :: value(nrows, * )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

     character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value(:nrows,:ncols) , units=units  )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatChSi


  subroutine parameterMatRealDpSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    real(dp) , intent(in) :: value(:, : )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

     character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units , fmt=fmt )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatRealDpSh

  subroutine parameterMatRealSpSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role , units ,fmt)

    type(xmlf_t), intent(inout)              :: xf
    real(sp) , intent(in) :: value(:, : )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

     character(len=*), intent(in), optional :: units
     character(len=*), intent(in), optional :: fmt

    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units , fmt=fmt )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatRealSpSh

  subroutine parameterMatIntSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    integer , intent(in) :: value(:, : )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

     character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units  )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatIntSh

  subroutine parameterMatLgSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role  )

    type(xmlf_t), intent(inout)              :: xf
    logical , intent(in) :: value(:, : )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value   )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatLgSh

  subroutine parameterMatChSh &
    (xf, value,  name, id, title, dictRef, convention, ref, role , units )

    type(xmlf_t), intent(inout)              :: xf
    character(len=*) , intent(in) :: value(:, : )
    character(len=*), intent(in), optional :: name
    character(len=*), intent(in), optional :: id
    character(len=*), intent(in), optional :: title
    character(len=*), intent(in), optional :: dictRef
    character(len=*), intent(in), optional :: convention
    character(len=*), intent(in), optional :: ref
    character(len=*), intent(in), optional :: role

     character(len=*), intent(in), optional :: units
 
    call xml_NewElement(xf, "parameter")
    if (present(name)) call xml_addAttribute(xf, "name", name)
    if (present(id)) call xml_addAttribute(xf, "id", id)
    if (present(title)) call xml_addAttribute(xf, "title", title)
    if (present(dictRef)) call xml_addAttribute(xf, "dictRef", dictRef)
    if (present(convention)) call xml_addAttribute(xf, "convention", convention)
    if (present(ref)) call xml_addAttribute(xf, "ref", ref)
    if (present(role)) call xml_addAttribute(xf, "role", role)

    call stmAddValue(xf=xf, value=value , units=units  )
    call xml_EndElement(xf, "parameter")
  end subroutine parameterMatChSh


end module m_wcml_parameter

