! This file is AUTOGENERATED!!!!
! Do not edit this file; edit m_dom_types.m4 and regenerate.
!
module m_dom_types


  type DOMImplementation
    character, pointer :: id(:)
  end type DOMImplementation

  type Node
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
  end type Node

  type NodeList
    type(Node), pointer :: list(:)
    integer :: length
  end type NodeList

  type NamedNodeMap
    type(Node), pointer :: list(:)
    integer :: length
  end type NamedNodeMap

  type DocumentFragment
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
  end type DocumentFragment

  type Document
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    type(DocumentType), pointer :: doctype
    type(DOMImplementation), pointer :: implementation
    type(Element), pointer :: documentElement
  end type Document

  type CharacterData
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: data(:)
    integer :: length
  end type CharacterData

  type Attr
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: name(:)
    logical :: specified
    character, pointer :: value
    ! Introduced in DOM Level 2
    type(Element), pointer :: ownerElement
  end type Attr

  type Element
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: tagName(:)
  end type Element

  type Text
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: data(:)
    integer :: length
  end type Text

  type Comment
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: data(:)
    integer :: length
  end type Comment

  type CDataSection
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: data(:)
    integer :: length
  end type CDataSection

  type DocumentType
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: name(:)
    type(namedNodeMap), pointer :: entities
    type(namedNodeMap), pointer :: notations
    character, pointer :: publicId(:)
    character, pointer :: systemId(:)
    character, pointer :: internalSubset(:)
  end type DocumentType

  type Notation
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: publicId(:)
    character, pointer :: systemId(:)
  end type Notation

  type Entity
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: publicId(:)
    character, pointer :: systemId(:)
    character, pointer :: notationName(:)
  end type Entity

  type EntityReference
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
  end type EntityReference

  type ProcessingInstruction
    character, pointer, dimension(:)         :: nodeName    
    character, pointer, dimension(:)         :: nodeValue   
    integer              :: nc              = 0 
    integer              :: nodeType        = 0
    type(Node), pointer :: parentNode      => null()
    type(Node), pointer :: firstChild      => null()
    type(Node), pointer :: lastChild       => null()
    type(Node), pointer :: previousSibling => null()
    type(Node), pointer :: nextSibling     => null()
    type(Document), pointer :: ownerDocument   => null()
    type(namedNodeMap), pointer :: attributes => null()
    type(nodeList), pointer :: childNodes  => null()  ! New
    ! Introduced in DOM Level 2:
    character, pointer, dimension(:) :: namespaceURI 
    character, pointer, dimension(:) :: prefix 
    character, pointer, dimension(:) :: localName
    character, pointer :: target(:)
    character, pointer :: data(:)
  end type ProcessingInstruction

  public :: Node
  public :: DocumentFragment
  public :: Document
  public :: CharacterData
  public :: Attr
  public :: Element
  public :: Text
  public :: Comment
  public :: CDataSection
  public :: DocumentType
  public :: Notation
  public :: Entity
  public :: EntityReference
  public :: ProcessingInstruction

end module m_dom_types
