module m_wxml_overloads

! FIXME this file should be autogenerated, it's too fragile.
  
  use m_common_format, only: str
  use m_wxml_core, only: xmlf_t
  use m_wxml_core, only: xml_AddCharacters
  use m_wxml_core, only: xml_AddAttribute
  use m_wxml_core, only: xml_AddPseudoAttribute

  implicit none
  private

  integer, parameter ::  sp = selected_real_kind(6,30)
  integer, parameter ::  dp = selected_real_kind(14,100)

  interface xml_AddCharacters
    module procedure xml_AddCharacters_SP
    module procedure xml_AddCharacters_DP
    module procedure xml_AddCharacters_Int
    module procedure xml_AddCharacters_Log
    module procedure xml_AddCharacters_SP_array
    module procedure xml_AddCharacters_DP_array
    module procedure xml_AddCharacters_Int_array
    module procedure xml_AddCharacters_Log_array
    module procedure xml_AddCharacters_Ch_array
  end interface

  interface xml_AddAttribute
    module procedure xml_AddAttribute_SP
    module procedure xml_AddAttribute_DP
    module procedure xml_AddAttribute_Int
    module procedure xml_AddAttribute_Log
    module procedure xml_AddAttribute_SP_array
    module procedure xml_AddAttribute_DP_array
    module procedure xml_AddAttribute_Int_array
    module procedure xml_AddAttribute_Log_array
    module procedure xml_AddAttribute_Ch_array
  end interface

  interface xml_AddPseudoAttribute
    module procedure xml_AddPseudoAttribute_SP
    module procedure xml_AddPseudoAttribute_DP
    module procedure xml_AddPseudoAttribute_Int
    module procedure xml_AddPseudoAttribute_Log
    module procedure xml_AddPseudoAttribute_SP_array
    module procedure xml_AddPseudoAttribute_DP_array
    module procedure xml_AddPseudoAttribute_I_array
    module procedure xml_AddPseudoAttribute_L_array
    module procedure xml_AddPseudoAttribute_Ch_array
  end interface

  public :: xml_AddCharacters
  public :: xml_AddAttribute
  public :: xml_AddPseudoAttribute

contains

  subroutine xml_AddCharacters_sp(xf, data, fmt)
    type(xmlf_t), intent(inout)    :: xf
    real(kind=sp), intent(in)      :: data
    character(len=*), intent(in), optional :: fmt

    if (present(fmt)) then
      call xml_AddCharacters(xf, str(data, fmt))
    else
      call xml_AddCharacters(xf, str(data))
    endif

  end subroutine xml_AddCharacters_sp


  subroutine xml_AddCharacters_sp_array(xf, data, fmt)
    type(xmlf_t), intent(inout)    :: xf
    real(kind=sp), dimension(:), intent(in) :: data
    character(len=*), intent(in), optional :: fmt

    if (present(fmt)) then
      call xml_AddCharacters(xf, str(data, fmt))
    else
      call xml_AddCharacters(xf, str(data))
    endif

  end subroutine xml_AddCharacters_sp_array


  subroutine xml_AddCharacters_dp(xf, data, fmt)
    type(xmlf_t), intent(inout)    :: xf
    real(kind=dp), intent(in)      :: data
    character(len=*), intent(in), optional :: fmt

    if (present(fmt)) then
      call xml_AddCharacters(xf, str(data, fmt))
    else
      call xml_AddCharacters(xf, str(data))
    endif

  end subroutine xml_AddCharacters_dp


  subroutine xml_AddCharacters_dp_array(xf, data, fmt)
    type(xmlf_t), intent(inout)    :: xf
    real(kind=dp), dimension(:), intent(in) :: data
    character(len=*), intent(in), optional :: fmt

    if (present(fmt)) then
      call xml_AddCharacters(xf, str(data, fmt))
    else
      call xml_AddCharacters(xf, str(data))
    endif

  end subroutine xml_AddCharacters_dp_array


  subroutine xml_AddCharacters_log(xf, data)
    type(xmlf_t), intent(inout)    :: xf
    logical, intent(in)            :: data

    call xml_AddCharacters(xf, str(data))

  end subroutine xml_AddCharacters_log

  subroutine xml_AddCharacters_log_array(xf, data)
    type(xmlf_t), intent(inout)    :: xf
    logical, dimension(:), intent(in)  :: data

    call xml_AddCharacters(xf, str(data))

  end subroutine xml_AddCharacters_log_array


  subroutine xml_AddCharacters_int(xf, data)
    type(xmlf_t), intent(inout)    :: xf
    integer, intent(in)            :: data

    call xml_AddCharacters(xf, str(data))

  end subroutine xml_AddCharacters_int


  subroutine xml_AddCharacters_int_array(xf, data)
    type(xmlf_t), intent(inout)    :: xf
    integer, dimension(:), intent(in) :: data

    call xml_AddCharacters(xf, str(data))

  end subroutine xml_AddCharacters_int_array

  subroutine xml_AddCharacters_Ch_array(xf, data, delimiter)
    type(xmlf_t), intent(inout)    :: xf
    character(len=*), dimension(:), intent(in) :: data
    character(len=1), intent(in), optional :: delimiter

    call xml_AddCharacters(xf, str(data, delimiter))

  end subroutine xml_AddCharacters_Ch_array


  subroutine xml_AddAttribute_SP(xf,name,value,fmt)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    real(kind=sp),    intent(in)  :: value
    character(len=*), intent(in), optional   :: fmt

    if (present(fmt)) then
      call xml_AddAttribute(xf,name,str(value,fmt))
    else
      call xml_AddAttribute(xf,name,str(value))
    endif

  end subroutine xml_AddAttribute_SP


  subroutine xml_AddAttribute_SP_array(xf,name,value,fmt)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    real(kind=sp),    intent(in), dimension(:)  :: value
    character(len=*), intent(in), optional   :: fmt

    if (present(fmt)) then
      call xml_AddAttribute(xf,name,str(value,fmt))
    else
      call xml_AddAttribute(xf,name,str(value))
    endif

  end subroutine xml_AddAttribute_SP_array


  subroutine xml_AddAttribute_DP(xf, name, value, fmt)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    real(kind=dp),    intent(in)  :: value
    character(len=*), intent(in), optional   :: fmt

    if (present(fmt)) then
      call xml_AddAttribute(xf,name,str(value,fmt))
    else
      call xml_AddAttribute(xf,name,str(value))
    endif

  end subroutine xml_AddAttribute_DP


  subroutine xml_AddAttribute_DP_array(xf, name, value, fmt)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    real(kind=dp),    intent(in), dimension(:)  :: value
    character(len=*), intent(in), optional   :: fmt

    if (present(fmt)) then
      call xml_AddAttribute(xf,name,str(value,fmt))
    else
      call xml_AddAttribute(xf,name,str(value))
    endif

  end subroutine xml_AddAttribute_DP_array

  subroutine xml_AddAttribute_log(xf, name, value)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    logical, intent(in)           :: value

    call xml_AddAttribute(xf,name,str(value))

  end subroutine xml_AddAttribute_log


  subroutine xml_AddAttribute_log_array(xf, name, value)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    logical, intent(in), dimension(:)           :: value

    call xml_AddAttribute(xf,name,str(value))

  end subroutine xml_AddAttribute_log_array


  subroutine xml_AddAttribute_int(xf, name, value)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    integer, intent(in)           :: value

    call xml_AddAttribute(xf,name,str(value))

  end subroutine xml_AddAttribute_int


  subroutine xml_AddAttribute_int_array(xf, name, value)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    integer, intent(in), dimension(:)           :: value

    call xml_AddAttribute(xf,name,str(value))

  end subroutine xml_AddAttribute_int_array


  subroutine xml_AddAttribute_Ch_array(xf, name, value, delimiter)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    character(len=*), intent(in), dimension(:)           :: value
    character(len=1), intent(in), optional :: delimiter

    call xml_AddAttribute(xf,name,str(value, delimiter))

  end subroutine xml_AddAttribute_Ch_array


  subroutine xml_AddPseudoAttribute_SP(xf, name, value, fmt)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    real(sp), intent(in)          :: value
    character(len=*), intent(in), optional :: fmt

    if (present(fmt)) then
      call xml_AddPseudoAttribute(xf,name,str(value,fmt))
    else
      call xml_AddPseudoAttribute(xf,name,str(value))
    endif
  end subroutine xml_AddPseudoAttribute_SP


  subroutine xml_AddPseudoAttribute_SP_array(xf, name, value, fmt)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    real(sp), intent(in), dimension(:) :: value
    character(len=*), intent(in), optional :: fmt

    if (present(fmt)) then
      call xml_AddPseudoAttribute(xf,name,str(value,fmt))
    else
      call xml_AddPseudoAttribute(xf,name,str(value))
    endif
  end subroutine xml_AddPseudoAttribute_SP_array


  subroutine xml_AddPseudoAttribute_DP(xf, name, value, fmt)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    real(dp), intent(in)          :: value
    character(len=*), intent(in), optional :: fmt

    if (present(fmt)) then
      call xml_AddPseudoAttribute(xf,name,str(value,fmt))
    else
      call xml_AddPseudoAttribute(xf,name,str(value))
    endif
  end subroutine xml_AddPseudoAttribute_DP


  subroutine xml_AddPseudoAttribute_DP_array(xf, name, value, fmt)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    real(dp), intent(in), dimension(:) :: value
    character(len=*), intent(in), optional :: fmt

    if (present(fmt)) then
      call xml_AddPseudoAttribute(xf,name,str(value,fmt))
    else
      call xml_AddPseudoAttribute(xf,name,str(value))
    endif
  end subroutine xml_AddPseudoAttribute_DP_array


  subroutine xml_AddPseudoAttribute_Int(xf, name, value)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    integer, intent(in)           :: value

    call xml_AddPseudoAttribute(xf, name, str(value))
  end subroutine xml_AddPseudoAttribute_Int


  subroutine xml_AddPseudoAttribute_I_array(xf, name, value)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    integer, intent(in), dimension(:) :: value

    call xml_AddPseudoAttribute(xf, name, str(value))
  end subroutine xml_AddPseudoAttribute_I_array


  subroutine xml_AddPseudoAttribute_Log(xf, name, value)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    logical, intent(in)           :: value

    call xml_AddPseudoAttribute(xf, name, str(value))
  end subroutine xml_AddPseudoAttribute_Log


  subroutine xml_AddPseudoAttribute_L_array(xf, name, value)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    logical, intent(in), dimension(:) :: value

    call xml_AddPseudoAttribute(xf, name, str(value))
  end subroutine xml_AddPseudoAttribute_L_array


  subroutine xml_AddPseudoAttribute_Ch_array(xf, name, value, delimiter)
    type(xmlf_t), intent(inout)   :: xf
    character(len=*), intent(in)  :: name
    character(len=*), intent(in), dimension(:) :: value
    character(len=1), intent(in), optional :: delimiter

    call xml_AddPseudoAttribute(xf, name, str(value, delimiter))
  end subroutine xml_AddPseudoAttribute_Ch_array

end module m_wxml_overloads

